package io.moquette.fce.model.info;

import com.google.gson.annotations.SerializedName;

/**
 * Enum which describes every type of info message.
 * 
 * @author lants1
 *
 */
public enum InfoMessageType {
	@SerializedName("GLOBAL_QUOTA_DEPLETED")
	GLOBAL_QUOTA_DEPLETED("GLOBAL_QUOTA_DEPLETED"),
	
	@SerializedName("PRIVATE_QUOTA_DEPLETED")
	PRIVATE_QUOTA_DEPLETED("PRIVATE_QUOTA_DEPLETED"),
	
	@SerializedName("REJECECTED_ACCORDING_TO_GLOBAL_RESTRICTIONS")
	GLOBAL_CONFIG_REJECTED("REJECECTED_ACCORDING_TO_GLOBAL_RESTRICTIONS"),
	
	@SerializedName("REJECECTED_ACCORDING_TO_PRIVATE_RESTRICTIONS")
	PRIVATE_CONFIG_REJECTED("REJECECTED_ACCORDING_TO_PRIVATE_RESTRICTIONS"),
	
	@SerializedName("MISSING_ADMIN_RIGHTS")
	MISSING_ADMIN_RIGHTS("MISSING_ADMIN_RIGHTS"),
	
	@SerializedName("PRIVATE_CONFIGURATION_CHANGE_ONLY_ALLOWED_FOR_OWN_USER")
	PRIVATE_CONFIG_CHANGE_ONLY_ALLOWED_FOR_OWN_USER("PRIVATE_CONFIGURATION_CHANGE_ONLY_ALLOWED_FOR_OWN_USER"),
	
	@SerializedName("TOPIC_CONFIGURATION_ACCEPTED")
	TOPIC_CONFIGURATION_ACCEPTED("TOPIC_CONFIGURATION_ACCEPTED"),
	
	@SerializedName("AUTHORIZATION_EXCEPTION")
	AUTHORIZATION_EXCEPTION("AUTHORIZATION_EXCEPTION");
	
	private String value;

    private InfoMessageType(String value)
    {
        this.value=value;
    }

    public String getValue()
    {
        return value;
    }
}
